spring:
  application:
    name: Login

  datasource:
    url: jdbc:mysql://localhost:3306/Login
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


#
#    logging:
#      level:
#        org.springframework.transaction.interceptor: TRACE
#        org.springframework.orm.jpa: DEBUG
#        org.springframework.transaction: DEBUG
#        org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG

server:
  port: 8088